name: Setup
on:
  workflow_dispatch:
      inputs:
        extra_tests:
          description: 'Enable additional CI tests'
          required: false
          default: 'true'
        components:
          description: Vulkan SDK Components
          required: false
          default: 'Vulkan-Headers Vulkan-Loader Vulkan-ExtensionLayer '
          # Vulkan-ValidationLayers robin-hood-hashing
        versions:
          description: Vulkan SDK Versions
          required: false
          default: '[ "1.4.321.0" ]'
        oses:
          description: 'Matrix OSes'
          required: true
          default: '[ "ubuntu-latest", "ubuntu-24.04-arm", "macos-latest" ]'
jobs:
  setup-all-matrix:
    if: ${{ github.event.inputs.extra_tests == 'true' || github.event.inputs.extra_tests == 'matrix' }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: ${{ fromJSON(github.event.inputs.oses) }}
        version: ${{ fromJSON(github.event.inputs.versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          vulkan-query-version: ${{ matrix.version }}
          vulkan-components: ${{ github.event.inputs.components }}
          vulkan-use-cache: true
      - name: Print runner configurations
        run: |
          echo runner os: ${{ runner.os }}, arch: ${{ runner.arch }}
      - name: Test Vulkan SDK Install
        shell: bash
        run: |
          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
          echo "VULKAN_SDK=='$VULKAN_SDK'"
          test -n "$VULKAN_SDK_VERSION"
          cmake -B tests/build -S tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=.
          cmake --build tests/build --config release
          ./tests/build/test_vulkan
